# This is a basic workflow to help you get started with Actions

name: upload_test

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        python_version: [3.6, 3.7, 3.8, 3.9]

    env:
      PYTHON_VERSION: ${{ matrix.python_version }}
      BUILD_PYTHON_MODULE: ON
      BUILD_APPIMAGE: OFF

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: ls

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact ${{ matrix.python_version }}
          path: README.md

